[workspace]
resolver = "2"

members = [
    "instasize",
    "instastack",
    "instawidth"
]

[workspace.dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
image = "0.25.5"
